### ISSUE TITLE
Allow multiple configs

### ISSUE THREAD

**Issue by klodeckl** [saro-lab/solr-db-importer#6]
Hi, your tool works great, thank you! I want to import multiple different data with different sql. For this it would be great to have multiple configs in the config file or an option to have the path of the config file as parameter on execution (like java -jar solr-db-importer-1.4.jar myconfig.xml). I prefer the second option.

**Comment by ac-saro** [comment]
Thank you for your opinion.
When time permits, I will include this feature.

**Comment by marker-seoul** [comment]
@klodeckl 
The relevant feature has been upgraded.
Please check version 1.5.
